#!/bin/bash
# session-end.sh - Generate detailed session summary on Stop event
# Hook type: Stop
# Triggers when: Claude finishes responding (main agent)
#
# Creates individual markdown files in .claude/sessions/ with git activity,
# modified files, and task progress for cross-session continuity.
# Replaces session-summary.sh with richer context capture.

set -e

# Read the input JSON from stdin
INPUT=$(cat)

# Only generate on end_turn (not on interrupts)
STOP_REASON=$(echo "$INPUT" | jq -r '.stop_hook_reason // "unknown"')
if [ "$STOP_REASON" != "end_turn" ]; then
    exit 0
fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
SESSIONS_DIR="$PROJECT_DIR/.claude/sessions"
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
SUMMARY_FILE="$SESSIONS_DIR/session_$TIMESTAMP.md"

mkdir -p "$SESSIONS_DIR"

# --- Git activity capture ---
CURRENT_BRANCH="(not a git repo)"
GIT_DIFF=""
MODIFIED_FILES=""
RECENT_COMMITS=""

if [ -d "$PROJECT_DIR/.git" ]; then
    CURRENT_BRANCH=$(cd "$PROJECT_DIR" && git branch --show-current 2>/dev/null || echo "detached")

    # Count available commits to avoid errors on shallow repos
    COMMIT_COUNT=$(cd "$PROJECT_DIR" && git rev-list --count HEAD 2>/dev/null || echo "0")
    LOOKBACK=5
    [ "$COMMIT_COUNT" -lt "$LOOKBACK" ] && LOOKBACK="$COMMIT_COUNT"

    if [ "$LOOKBACK" -gt 0 ]; then
        GIT_DIFF=$(cd "$PROJECT_DIR" && git diff --stat "HEAD~${LOOKBACK}..HEAD" 2>/dev/null | head -20 || true)
        MODIFIED_FILES=$(cd "$PROJECT_DIR" && git diff --name-only "HEAD~${LOOKBACK}..HEAD" 2>/dev/null | head -15 || true)
        RECENT_COMMITS=$(cd "$PROJECT_DIR" && git log --oneline -"$LOOKBACK" 2>/dev/null || true)
    fi
fi

# --- Task Master capture ---
TASK_PROGRESS=$(task-master list --status in-progress 2>/dev/null | head -10 || echo "No tasks in progress")

# --- Generate summary ---
cat > "$SUMMARY_FILE" << EOF
# Session Summary: $TIMESTAMP

## Branch: $CURRENT_BRANCH

## Recent Commits
\`\`\`
${RECENT_COMMITS:-No commits this session}
\`\`\`

## Files Modified
${MODIFIED_FILES:-No files modified}

## Git Activity
\`\`\`
${GIT_DIFF:-No changes detected}
\`\`\`

## Task Progress
${TASK_PROGRESS}

## Next Steps
<!-- Review and update before next session -->

---
*Generated by session-end.sh*
EOF

echo "Session summary saved to $SUMMARY_FILE"
exit 0
